name: logger
description: 'A Simple Logging Interface'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  logd: 0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
