name: logd
description: Modular hierarchical logging for Dart and Flutter. Features modular pipeline processing, O(1) configuration resolution, and lowâ€‘overhead performance.
version: 0.6.1
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
topics:
  - logging
  - logger
  - hierarchical
  - performance
  - structured-logging

license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  http: ^1.2.0
  meta: ^1.17.0
  timezone: ^0.11.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
