name: logd
description: A flexible Dart logging library for Flutter and standalone apps, featuring hierarchical loggers, customizable handlers, formatters, sinks, filters, stack trace integration, and timezone-aware timestamps for efficient debugging and monitoring.
version: 0.1.2
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
topics:
  - logging
  - dart-logger
  - flutter-logging
  - hierarchical-logging
  - debug-tools
license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
