name: logd
description: A professional, hierarchical logging library for Dart & Flutter. Features high-performance architecture, composable decorators, modular sinks, and thread-safe configuration.
version: 0.5.0
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
topics:
  - logging
  - logger
  - performance
  - hierarchical
  - debugging
license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
