name: logd
description: A logger daemon for Dart and Flutter.
version: 0.1.0
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
publish_to: https://pub.dev/packages/logd
topics: [ log, logger,  modular, daemon, demon, ]
license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
