name: logd
description: A modular high performance logging daemon for Dart and Flutter. Logger Tree Hierarchy with instantaneous synced cached configurations. Highly Customizable with Log Formatters, Filters, Sinks.
version: 0.1.3
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
topics:
  - logger
  - modular-logging
  - flutter-logger
  - hierarchical-logging
  - debug-tools
license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
