name: logd
description: A modular logging daemon for Dart and Flutter. Highly Customizable with Log Formatters, Filters, Sinks. Logger Tree Hierarchy with instantaneous configurations.
version: 0.1.6
repository: https://github.com/pooriaaskarim/logd
homepage: https://pub.dev/packages/logd
topics:
  - logger
  - modular-logging
  - flutter-logger
  - hierarchical-logging
  - debug-tools
license: BSD-3-Clause
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
