name: benchmarks
description: Benchmarks for the logd package.
publish_to: 'none'
version: 0.6.4
environment:
  sdk: '>=3.6.0 <4.0.0'
resolution: workspace

dependencies:
  benchmark_harness: ^2.4.0
  logd:
    path: ../logd
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
